SELECT * FROM dbo.dim_contribution_factor
select * from dbo.dim_date
select * from dbo.dim_location
select * from dbo.dim_source
select * from dbo.dim_time
select * from dbo.dim_vehicle
select * from dbo.fct_accident
select * from dbo.fct_contribution
select * from dbo.stg_cleaned_austin_data
select * from dbo.stg_cleaned_chicago_data
select * from dbo.stg_cleaned_ny_data